name: 清理旧 Releases 和 Tags

on:
  workflow_dispatch:
    inputs:
      keep_latest:
        description: '每个系列保留最近几个 tag（默认：15）'
        required: false
        default: '20'

jobs:
  cleanup:
    name: 清理 openwrt / immortalwrt / coolsnowwolf 标签
    runs-on: ubuntu-latest

    steps:
      - name: 安装 GitHub CLI
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq gh

      - name: 登录 GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: 清理各系列旧标签（保留最近 ${{ inputs.keep_latest }} 个）
        run: |
          KEEP_LATEST=${{ inputs.keep_latest }}

          for PROJECT in openwrt immortalwrt coolsnowwolf; do
            echo "🔍 正在处理 $PROJECT 系列标签..."

            TAGS=$(gh release list --limit 1000 --repo "${{ github.repository }}" | awk '{print $1}' | grep "${PROJECT}$" | sort -r)

            COUNT=$(echo "$TAGS" | wc -l)
            if [ "$COUNT" -le "$KEEP_LATEST" ]; then
              echo "✅ $PROJECT 系列仅有 $COUNT 个标签，无需清理。"
              continue
            fi

            echo "📦 $PROJECT 系列标签共 $COUNT 个，将删除 $((COUNT - KEEP_LATEST)) 个旧标签..."

            DELETE_TAGS=$(echo "$TAGS" | tail -n +$((KEEP_LATEST + 1)))
            for TAG in $DELETE_TAGS; do
              echo "::warning:: 删除 $PROJECT → $TAG"
              gh release delete "$TAG" -y --repo "${{ github.repository }}" || echo "⚠️ Release $TAG 不存在或删除失败"
              gh tag delete "$TAG" --repo "${{ github.repository }}" || echo "⚠️ Tag $TAG 删除失败"
            done
          done
