name: 清理旧标签（保留每个系列最近 20 个）

on:
  workflow_dispatch:

jobs:
  clean_tags:
    runs-on: ubuntu-latest
    steps:
      - name: 安装 GitHub CLI
        run: sudo apt-get update -qq && sudo apt-get install -y -qq gh

      - name: 登录 GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: 清理每个系列旧 tag（真正删除远程标签）
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP: 20
        run: |
          set -e

          gh repo view --json nameWithOwner

          SERIES=("openwrt" "immortalwrt" "coolsnowwolf")

          for PROJECT in "${SERIES[@]}"; do
            echo "🔍 正在处理 $PROJECT 系列标签..."

            # 获取所有该系列的 tag，按时间倒序（最新在前）
            TAGS=$(gh api repos/${{ github.repository }}/tags | jq -r '.[].name' | grep "$PROJECT$" | sort -r)

            COUNT=$(echo "$TAGS" | wc -l)
            if [ "$COUNT" -le "$KEEP" ]; then
              echo "✅ $PROJECT 系列仅有 $COUNT 个标签，无需清理。"
              continue
            fi

            # 要删除的 tag 列表
            DELETE_TAGS=$(echo "$TAGS" | tail -n +$(($KEEP + 1)))

            echo "$DELETE_TAGS" | while read TAG; do
              echo "🗑️ 正在删除远程标签 $TAG"
              git push origin :refs/tags/$TAG || true
              gh api -X DELETE repos/${{ github.repository }}/releases/tags/$TAG || echo "⚠️ 无 Release 页面"
            done
          done
